from tkinter import *
from tkinter import ttk
import random
import string
#*************************************
def genpass():
    l7.config(text="")
    
    upper=random.sample(string.ascii_uppercase,v3.get())
    lower=random.sample(string.ascii_lowercase,v4.get())
    symbols=random.sample(string.punctuation,v5.get())
    digits=random.sample(string.digits,v6.get())
    total=upper+lower+symbols+digits
    total=random.sample(total,len(total))
    total=''.join(total)
    l7.config(text=total,fg="orange")
#***************************************
root=Tk()
root.title("PASSWORD GENERATOR")
root.geometry("300x320")
root.resizable(0,0)
root.configure(bg="navyblue")
l1=Label(root,text="PASSWORD GENERATOR",font=('Times New Roman',18,'bold'),bg='black',fg='magenta')
l1.pack(ipadx=5,ipady=5,fill=BOTH)
l2=Label(root,text="GIVE THE COMPONENTS OF PASSWORD",font=('Calibri',12,'bold'),bg="dark blue",fg="gold")
l2.pack(ipadx=3,ipady=3,fill=Y,pady=5)
l3=Label(root,text="UPPER CASE",font=("Bookman Old Style",12,'bold'),bg="beige")
l3.place(x=20,y=100)
v3=IntVar()
e3=Entry(root,width=20,textvariable=v3)
e3.place(x=150,y=103)
e3.focus()
l4=Label(root,text="LOWER CASE",font=("Bookman Old Style",12,'bold'),bg="beige")
l4.place(x=20,y=135)
v4=IntVar()
e4=Entry(root,width=20,textvariable=v4)
e4.place(x=150,y=138)
l5=Label(root,text="SYMBOLS",font=("Bookman Old Style",12,'bold'),bg="beige")
l5.place(x=20,y=170)
v5=IntVar()
e5=Entry(root,width=20,textvariable=v5)
e5.place(x=150,y=173)
l6=Label(root,text="DIGITS",font=("Bookman Old Style",12,'bold'),bg="beige")
l6.place(x=20,y=205)
v6=IntVar()
e6=Entry(root,width=20,textvariable=v6)
e6.place(x=150,y=208)
b1=Button(root,text="CANCEL",font=("Bookman Old Style",10,'bold'),width=8,bg="red",command=root.destroy)
b1.place(x=50,y=240)
b1=Button(root,text="GENERATE",font=("Bookman Old Style",10,'bold'),width=8,bg="green",command=genpass)
b1.place(x=180,y=240)
l6=Label(root,text="PASSWORD",font=("Bookman Old Style",12,'bold'),bg="beige")
l6.place(x=20,y=280)
l7=Label(root,text="",font=("Bookman Old Style",12,'bold'),bg="dark blue")
l7.place(x=150,y=280)
root.mainloop()
